project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - text: "Home"
            file: index.qmd
          - text: "About Me"
            file: about.qmd
          - text: "Publications"
            file: publications.qmd
      - section: "Workshops"
        contents:
          - text: "Introduction ggplot"
            file: workshops/intro_into_ggplot.qmd
          - text: "Simple R"
            file: workshops/simple_R.qmd
          - text: "Simple R2"
            file: workshops/simple_R.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
