project:
  type: website

website:
  title: "David Jansen"
  navbar:
    left:
      - href: qmd/index.qmd
        text: Home
      - qmd/dabout.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



