project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home
        url: index.qmd
      - text: About
        url: about.qmd
      - text: simple R  
        url: simple_R.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
