project:
  type: website

website:
  title: "David Jansen"
  navbar:
    left:
      - href: qmd_files/index.qmd
        text: Home
      - qmd_files/about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

source_dir: qmd_files    





