project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - text: "Home"
            file: index.qmd
          - text: "About Me"
            file: about.qmd
          - text: "Publications"
            file: publications.qmd
      - section: "Workshops"
        contents:
          - text: "Introduction ggplot"
            file: ./workshops/intro_into_ggplot.qmd
          - text: "Introduction into git version control" 
            file: ./workshops/git_version_control.qmd
          - text: "Introduction into good data and coding practices"
            file: ./workshops/good_data_practises.qmd
          #- text: "Reproducibility research"
          #  file: ./workshops/reproducibility_workshop.qmd
      - section: "Workshops"
          contents:
            - text: "CV"
              file: ./workshops/CV.qmd 
            - text: "Resume"
              file: ./workshops/resume.qmd
      - section: "Presentations"
          contents:
            - text: "MCEVBD interview"
              file: ./workshops/CV.qmd 
            - text: "Resume"
              file: ./workshops/resume.qmd                                                                                        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
