project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
<<<<<<< HEAD
      - text: Home
        url: qmd_files/index.qmd
      - text: About
        url: qmd_files/about.qmd 
      - text: Publications
        url: qmd_files/publications.qmd         
      - text: Simple R
        url: qmd_files/simple_R.qmd
      - text: Introduction into Git version control
        url: qmd_files/git_version_control.qmd
=======
      - section: "Basic"
        contents:
          - text: Home
            url: qmd_files/index.qmd
          - text: About
            url: qmd_files/about.qmd 
          - text: Publications
            url: qmd_files/publications.qmd         
>>>>>>> origin/main

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
