project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home
        url: qmd_files/index.qmd
      - text: About
        url: qmd_files/about.qmd 
      - text: Publications
        url: qmd_files/publications.qmd         
      - text: Workshops
        submenu:
          - text: Simple R
            url: qmd_files/simple_R.qmd              

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true