project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - text: "Home"
            file: index.qmd
          - text: "About Me"
            file: about.qmd
          - text: "Publications"
            file: publications.qmd
          - text: "Presentations"
            file: presentations.qmd
      - section: "Workshops"
        contents:
          - text: "Introduction into good data and coding practices"
            file: ./workshops/good_data_practises.qmd
          - text: "Introduction into git version control" 
            file: ./workshops/git_version_control.qmd
          - text: "Reproducibility research"
            file: ./workshops/reproducibility_workshop.qmd
          - text: "Peer review process"
            file: ./workshops/peer_review.qmd
          - text: "Introduction to data management for MCEVBD fellows"            
          - file: workshops/good_data_practises_for_MCEVBD_fellows.qmd

bibliography: publications.bib         

format:
  html:
    theme: cosmo
    css: ./styles/styles.css
    toc: true
