project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - qmd_files/index.qmd
          - qmd_files/about.qmd
          - qmd_files/publications.qmd
      - section: "Layout"
        contents:
          - text: "ggplot"
            file: qmd_files/intro_into_ggplot.qmd
          - text: "Simple R"
            file: qmd_files/simple_R.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
