project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - text: "Home"
            file: index.qmd
          - text: "About Me"
            file: about.qmd
          - text: "About Me2"
            file: about2.qmd
          - text: "Publications"
            file: publications.qmd
      - section: "Workshops"
        contents:
          - text: "Introduction into good data and coding practices"
            file: ./workshops/good_data_practises.qmd
          - text: "Introduction ggplot"
            file: ./workshops/intro_into_ggplot.qmd
          - text: "Introduction into git version control" 
            file: ./workshops/git_version_control.qmd
          - text: "Reproducibility research"
            file: ./workshops/reproducibility_workshop.qmd
      - section: "Presentations"
        contents:
          - text: "MCEVBD interview"
            file: ./presentations/MCEVBD_interview.qmd
      - section: "Other"
        contents:
          - text: "CV"
            file: ./other/CV.qmd 
          - text: "Resume"
            file: ./other/resume.qmd

bibliography: publications.bib         

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
