project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home
        url: index.qmd
      - text: About
        url: about.qmd        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true