name: Check Docker Image Availability

on:
  workflow_dispatch:

jobs:
  check-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker image availability
        run: docker images my_local_docker:latest