name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:         ## only change if a change to a qmd file is pushed.
      - '**/*.ylm' # This matches any qmd file in any subdirectory

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
