name: R Package Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mydocker:
        image: djanen1979/david-awam-jansen.github.io:latest

    steps:
    - name: Start Docker container
      run: docker start mydocker || true  # Start the container if not already running 

    - name: List Docker containers
      run: docker ps -a 

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Copy R library from container
      run: |
        docker cp mydocker:/usr/local/lib/R/site-library/ $HOME/R_packages

    - name: Set up R environment
      run: |
        echo "R_LIBS=$HOME/R_packages:/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library" >> $GITHUB_ENV

    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}