name: Print Commit Message

on:
  push:
    branches:
      - main

jobs:
  print-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print Commit Message
        run: echo "The triggering commit message is: ${{ github.event.head_commit.message }}"
